jms:
  process:
    queue:
      start: moj.pam.process.start
      signal: moj.pam.process.signal
  ekp:
    queue:
      getmessageids:  moj.dm.fuse.getmessage
      startretrievemessage: moj.pam.camel.startretrievemessage
      startmessageids: moj.dm.fuse.startmessage
      confirmMessageId: moj.rm.fuse.confirmmessage
      fetchMessageId:  moj.rm.fuse.fetchmessage
      errorHospital: moj.fh.fuse.submit
      triggerPrepareMessage: moj.pm.fuse.preparemessage
      validateDataBySchema: moj.pm.fuse.validate
      scanMessage: moj.pm.fuse.scan
      buildAdditionalAttachmentRelations: moj.pm.fuse.build
      fillMetadata: moj.pm.fuse.fillmetadata
      detectLegalApplications: moj.pm.fuse.legalapps
      checkERV: moj.pm.fuse.checkerv
      determineSenderRoles: moj.pm.fuse.roles
      storeProcessingDataRepresentation: moj.pm.fuse.storedata
      notifyMessageReceived: moj.pm.fuse.notify
      finishAblaufdatenSetVerarbeitet:  moj.pm.fuse.setend
      findUpdate: moj.pm.fuse.findupdate
#amqphub:
#  amqp10jms:
#    remoteUrl: amqp://localhost:5672
#    pool:
#      enabled: true

cxf:
  path: /rest
jbpm:
  executor:
    enabled: false
kieserver:
  casemgmt:
    enabled: true
  dmn:
    enabled: true
  drools:
    enabled: true
  swagger:
    enabled: true  
  jbpm:
    enabled: true
  jbpmui:
    enabled: true
  location: http://localhost:8090/rest/server
  serverId: ekp-pam-server
  serverName: ekp-pam-server
  controllers: ws://localhost:8085/business-central/websocket/controller
server:
  address: 0.0.0.0
  port: 8090
spring:
  artemis:
    mode: native
    host: localhost
    port: 61616
    pool:
      enabled: true
    max-connections: 50
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    password: sa
    url: jdbc:h2:mem:ekp-pam-db
    username: sa
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: update
        show_sql: false
  jta:
    narayana:
      transaction-manager-id: 1

# Define KJARs to deploy here
deployment:
  kjars:
    - alias: ekp-workflows
      artifactId: ekp-workflows
      containerId: ekp-workflows
      groupId: org.redhat.moj
      version: 1.0.0-SNAPSHOT

logging:
  level:
    org:
#      springframework:
#        transaction: TRACE
#        jms:
#          connection: TRACE
      eclipse: WARN
      redhat: DEBUG
